### ISSUE TITLE
DWLS package installation error

### ISSUE THREAD

**Issue by sumanm99** [dtsoucas/DWLS#13]
I was trying to install the DWLS package in R via **devtools::install_bitbucket("yuanlab/dwls", ref="master")**. But the installation gives this error **Error: object 'zlm.SingleCellAssay' is not exported by 'namespace:MAST'**.

The available versions of MAST do not export SingleCellAssay. So, this error cannot be resolved by installing any of the MAST package versions either.

Below you can find a screenshot of the error generated in R. Could you please tell a way to resolve this? 
[link](https://ibb.co/Yc7WGK4)
I hope to get a reply from you at the earliest.

Thank you.

**Comment by sistia01** [comment]
Hello, thank you for your interest in DWLS. 

We are in the process of updating DWLS, the main repo has moved [here](https://github.com/sistia01/DWLS). Would you mind trying to install the package this way: 

`` library(devtools)``
`` install_github("sistia01/DWLS")``

Let me know if you have any issues.

**Comment by sumanm99** [comment]
Dear, 

The package installation was successful.

But there are errors generated with buildSignatureMatrixMast() when I run it on my single cell data matrix. This issue has been reported previously too https://github.com/dtsoucas/DWLS/issues/7. 

Could you please suggest ways to overcome this error? You can find a screenshot of the same below.

![image](https://user-images.githubusercontent.com/104161349/167279696-133a4e4d-09cb-48d6-b55f-a11eee5629bb.png)

I have used a single cell RNAseq matrix with the labels as the Cell types of that reference data.

**Comment by poseidonchan** [comment]
> Hello, thank you for your interest in DWLS. 
> 
> 
> 
> We are in the process of updating DWLS, the main repo has moved [here](https://github.com/sistia01/DWLS). Would you mind trying to install the package this way: 
> 
> 
> 
> `` library(devtools)``
> 
> ``githubinstall("sistia01/DWLS")``
> 
> 
> 
> Let me know if you have any issues. 

Should it be install_github()?😅

**Comment by sumanm99** [comment]
> f you have any issues.
