### ISSUE TITLE
bulk normalization methods

### ISSUE THREAD

**Issue by qingnanl** [dtsoucas/DWLS#2]
Dear DWLS team,

Thanks for making the package. I am interested in what bulk RNA-seq normalization method could be used for this package. In the paper, I noticed that you all used FPKM for bulk. You also mentioned that the single-cell normalization is critical. For bulk, have you tested other normalizations, such as raw counts or TPM/CPM?

Thanks,

qingnan

**Comment by dtsoucas** [comment]
We have not tried other approaches, but would be curious to know how performance changes using other bulk normalization approaches.
