### ISSUE TITLE
Unable to install with newer version of MAST

### ISSUE THREAD

**Issue by Keaty19** [dtsoucas/DWLS#4]
Hi there,

I am currently trying to install the DWLS package, but keep getting the error:

`Error: object 'zlm.SingleCellAssay' is not exported by 'namespace:MAST'`

Because of the newer versions of MAST no longer containing the zlm.SingleCellAssay function ([https://bioconductor.org/packages/devel/bioc/manuals/MAST/man/MAST.pdf] page 34) and being replaced with `zlm`.

Is there a way of working around this? Or will it be a case of having to install an older version of MAST (v 0.931 for example). If so, do you know of any repositories which contain the old code?

Thank you!

Sam

**Comment by dtsoucas** [comment]
Should now be fixed with the latest updates! `zlm.SingleCellAssay` has been replaced with `zlm`. Thank you!

**Comment by annavpo** [comment]
Hello,

I am also trying to install the DWLS package with devtools::install_bitbucket("yuanlab/dwls")
and I get the same error as people have mentioned before: 

Error: object 'zlm.SingleCellAssay' is not exported by 'namespace:MAST'

The "MAST version I use is '1.16.0'
